language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO='Django<1.6'
  - DJANGO='Django<1.7'
  - DJANGO='https://github.com/django/django/archive/1.7b1.tar.gz'
matrix:
  exclude:
    - python: "2.6"
      env: "DJANGO='https://github.com/django/django/archive/1.7b1.tar.gz'"
install:
  - 'pip install "${DJANGO}"'
  - pip install coveralls
  - pip install .
script: ./runtests.sh -v
after_success:
  - coveralls
